### ISSUE TITLE
Support parentheses style attribute dictionaries

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/django-hamlpy#17]
From: http://haml.info/docs/yardoc/file.REFERENCE.html

HAML supports an alternative syntax like:

```%a(class="foo bar" id="bar")```

I like this MUCH more because:

1. It uses ='s around key/value pairs just like HTML attributes
2. It doesn't have commas around key/values just like HTML
3. It doesn't use {} like Django does, so it is clearer which parts are HAML and which are Django

Compare these two:

```
%a.btn.btn-primary( style="float:right; margin-left:10px" href="{% url 'orgs.topup_create' %}?org={{ org.id }}" ) Add TopUp
```

And

```
%a.btn.btn-primary{ style:"float:right; margin-left:10px", href:"{% url 'orgs.topup_create' %}?org={{ org.id }}" } Add TopUp
```

Former is a lot nicer in my opinion.

**Comment by Psycojoker** [comment]
I like it too, the "no comma" part is a good win for me since it makes converting from html way easier.

I'll happily merge a PR adding this feature (don't have time to do that right now).

**Comment by rowanseymour** [comment]
Added in #29
