### ISSUE TITLE
PEP 8 Issues

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/django-hamlpy#4]
How do we feel about cleaning up some of the many PEP issues and using flake8 as part of the CI build?

**Comment by Psycojoker** [comment]
There is a lot of cleaning around that can be done (in addition of pep8) but I would prefer that we check [the list of PR on jessemiller repository](https://github.com/jessemiller/HamlPy/pulls) first and see which ones we want to merge and to do the cleaning after to reduce the number of conflicts.

This will ease our work I think.

**Comment by rowanseymour** [comment]
Makes sense

**Comment by rowanseymour** [comment]
Addressed in #32
