### ISSUE TITLE
Text in a %style tag should not be changed

### ISSUE THREAD

**Issue by Kangaroux** [nyaruka/django-hamlpy#50]
To be more specific, any text in `%style` tags that use the `.class` or `#id` syntax should not be replaced with divs.

```haml
:css
  .myclass {
    color: red;
  }

%style(type="text/css")
  .myclass {
    color: red;
  }
```

Gets converted to

```html
<style type='text/css'>
  .myclass {
    color: red;
  }
</style>

<style type='text/css'>
  <div class='myclass'>{    color: red;
</div>
  }
</style>
```

This is probably also an issue with `%script` but I haven't run into it.

**Comment by rowanseymour** [comment]
Interesting. Do we know what the real haml library does in this case?

**Comment by Kangaroux** [comment]
I can't imagine a scenario where this would ever be the intended result.

**Comment by rowanseymour** [comment]
Sure it's just not entirely clear how the content of a style tag should be handled if not like regular haml. For example, we'd still want to parse django tags, comments etc:

```haml
%style(type="text/css")
  -# this is comment
  -if something
    .myclass { color: red; }
```

And the same problem exists for other elements, e.g.

```haml
%script(type="text/javascript")
  foo = bar
    .length()
```

And ultimately thats why filters like `:css` and `:javascript` exist so that segments of the haml file can be handled as something other than haml.

**Comment by nicpottier** [comment]
Ya, agree that this is the entire reason for `:css` and `:javascript`. Current behavior feels right to me.

**Comment by rowanseymour** [comment]
Also worth noting that for any little snippets where `:css` and `:javascript` don't suffice and you really need to use the `%script` and `%style` elements (e.g. you want to use django tags) - you can escape a line with `\` to ensure it's not parsed as Haml.

**Comment by rowanseymour** [comment]
Also you can do

```haml
%style{ ... }
  :plain
    .myclass {
       color: red;
    }
```
